FROM bradjones/dotnet-ide:latest
LABEL maintainer "brad@bjc.id.au"

# Download and extract rider
RUN cd /opt && \
    curl -L `echo -n \`curl -s 'https://data.services.jetbrains.com/products/releases?code=RD&latest=true&type=eap' | jq -r '.RD[0].downloads.linux.link'\`` | \
    tar xz && \
    mv `ls` rider