#!/usr/bin/env bash
self=$(readlink -f $0); tasks=`dirname ${self}`; projectRoot=`dirname ${tasks}`;
docker build -t bradjones/dotnet:latest -t bradjones/dotnet:`date +%Y%m%d` -f Dockerfile.dotnet $projectRoot;
docker build -t bradjones/dotnet-ide:latest -t bradjones/dotnet-ide:`date +%Y%m%d` -f Dockerfile.dotnet-ide $projectRoot;
docker build -t bradjones/dotnet-vscode:latest -t bradjones/dotnet-vscode:`date +%Y%m%d` -f Dockerfile.dotnet-vscode $projectRoot;
docker build -t bradjones/dotnet-rider:latest -t bradjones/dotnet-rider:`date +%Y%m%d` -f Dockerfile.dotnet-rider $projectRoot;
