#!/usr/bin/env bash
self=$(readlink -f $0); tasks=`dirname ${self}`; projectRoot=`dirname ${tasks}`;
docker push bradjones/dotnet;
docker push bradjones/dotnet-ide;
docker push bradjones/dotnet-vscode;
docker push bradjones/dotnet-rider;
